const API_URL = process.env.NEXT_PUBLIC_API_URL || "http://localhost:5000/api"; export interface User { id: string; email: string; name?: string; role: "USER" | "ADMIN";
} export interface AuthResponse { token: string; user: User;
} export interface Signal { id: string; symbol: string; type: "INTRADAY" | "SWING" | "POSITIONAL"; entryPrice: number | string; target1: number | string; target2: number | string | null; stopLoss: number | string; status: "ACTIVE" | "TARGET_HIT" | "STOPLOSS_HIT" | "EXITED"; notes?: string; postedAt: string; isMasked?: boolean;
} export interface Blog { id: string; title: string; slug: string; content: string; category: string; tags: string[]; author: string; published: boolean; publishedAt: string;
} export interface Testimonial { id: string; clientName: string; review: string; rating: number; clientRole?: string; avatarUrl?: string;
} export interface Lead { id: string; name: string; email: string; phone: string; service: string; message: string; isRead: boolean; createdAt: string;
} export function getAuthToken(): string | null { if (typeof window !== "undefined") { return localStorage.getItem("brahmastra_token"); } return null;
} export function setAuthToken(token: string) { if (typeof window !== "undefined") { localStorage.setItem("brahmastra_token", token); }
} export function removeAuthToken() { if (typeof window !== "undefined") { localStorage.removeItem("brahmastra_token"); localStorage.removeItem("brahmastra_user"); }
} export function getLoggedUser(): User | null { if (typeof window !== "undefined") { const userStr = localStorage.getItem("brahmastra_user"); return userStr ? JSON.parse(userStr) : null; } return null;
} export function setLoggedUser(user: User) { if (typeof window !== "undefined") { localStorage.setItem("brahmastra_user", JSON.stringify(user)); }
} // Fallback high-fidelity mocks for immediate demonstration
const mockSignals: Signal[] = [ { id: "sig-1", symbol: "RELIANCE", type: "INTRADAY", entryPrice: 2450.5, target1: 2475.0, target2: 2490.0, stopLoss: 2432.0, status: "ACTIVE", notes: "Bullish breakout above 15-min consolidation range.", postedAt: new Date(Date.now() - 3600000).toISOString(), }, { id: "sig-2", symbol: "TCS", type: "SWING", entryPrice: 3820.0, target1: 3950.0, target2: 4050.0, stopLoss: 3730.0, status: "ACTIVE", notes: "Double bottom breakout on daily charts.", postedAt: new Date(Date.now() - 12000000).toISOString(), }, { id: "sig-3", symbol: "INFY", type: "INTRADAY", entryPrice: 1420.0, target1: 1445.0, target2: null, stopLoss: 1405.0, status: "TARGET_HIT", notes: "Target 1 hit in first 30 minutes of trade.", postedAt: new Date(Date.now() - 86400000).toISOString(), },
]; const mockBlogs: Blog[] = [ { id: "blog-1", title: "Mastering Intraday Risk Management", slug: "mastering-intraday-risk-management", content: "Risk management is the absolute key to surviving as an intraday trader. Never risk more than 1% of your total capital on a single trade. Implement hard stop losses inside the broker system directly, avoiding emotional delays. Always look for a risk-reward ratio of at least 1:2 to ensure long-term mathematical profitability.", category: "Trading Psychology", tags: ["Risk Management", "Intraday Trading Tips", "Trading Psychology"], author: "Brahmastra Head Analyst", published: true, publishedAt: new Date(Date.now() - 86400000 * 2).toISOString(), }, { id: "blog-2", title: "NIFTY Outlook and Swing Trading Setups", slug: "nifty-outlook-and-swing-trading-setups", content: "The broader market NIFTY 50 has shown persistent consolidation at the key daily moving averages. We are monitoring price action closely for breakouts above key resistance zones. Swing trading opportunities are opening up in defensive sectors like FMCG and Pharmaceuticals. Key support is set at 22,100 points.", category: "Market Analysis", tags: ["Nifty 50", "Swing Trading Advisory", "Technical Analysis"], author: "Brahmastra Technical Analyst", published: true, publishedAt: new Date(Date.now() - 86400000 * 5).toISOString(), },
]; const mockTestimonials: Testimonial[] = [ { id: "test-1", clientName: "Rahul Sharma", review: "Brahmastra's intraday advisory is extremely precise. I've seen a consistent 15% monthly growth in my active trading capital since joining the Pro Plan.", rating: 5, clientRole: "Active Trader", }, { id: "test-2", clientName: "Priya Patel", review: "Excellent support! The portfolio management guidance helped me restructure my mutual funds and equity holdings for maximum tax-efficient growth.", rating: 5, clientRole: "IT Professional & Part-time Investor", },
]; export async function apiFetch<T>(endpoint: string, options: RequestInit = {}): Promise<T> { const token = getAuthToken(); const headers = { "Content-Type": "application/json", ...(token ? { Authorization: `Bearer ${token}` } : {}), ...(options.headers || {}), }; try { const res = await fetch(`${API_URL}${endpoint}`, { ...options, headers, }); if (!res.ok) { const errorData = await res.json().catch(() => ({})); throw new Error(errorData.error || `HTTP error! status: ${res.status}`); } return await res.json(); } catch (err: any) { console.warn(`API call failed for ${endpoint}. Returning mockup fallback. Error: ${err.message}`); /* Mock routers fallback */ if (endpoint.startsWith("/signals")) { return mockSignals as unknown as T; } if (endpoint.startsWith("/blogs/slug")) { const slug = endpoint.split("/").pop(); const blog = mockBlogs.find(b => b.slug === slug); if (!blog) throw new Error("Blog not found"); return blog as unknown as T; } if (endpoint.startsWith("/blogs")) { return mockBlogs as unknown as T; } if (endpoint.startsWith("/leads") && options.method === "POST") { return { message: "Thank you for contacting us. (Mocked Success)" } as unknown as T; } throw err; }
}
